steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portal-warp-api:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portal-warp-api:$SHORT_SHA'
      - '.'

  # Push to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/portal-warp-api:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/portal-warp-api:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portal-warp-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/portal-warp-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'MONGODB_URI=${_MONGODB_URI},MONGODB_DB_NAME=${_MONGODB_DB_NAME},JWT_SECRET_KEY=${_JWT_SECRET_KEY},JWT_ALGORITHM=${_JWT_ALGORITHM},ACCESS_TOKEN_EXPIRE_MINUTES=${_ACCESS_TOKEN_EXPIRE_MINUTES},REFRESH_TOKEN_EXPIRE_DAYS=${_REFRESH_TOKEN_EXPIRE_DAYS},CORS_ORIGINS=${_CORS_ORIGINS}'

images:
  - 'gcr.io/$PROJECT_ID/portal-warp-api:latest'
  - 'gcr.io/$PROJECT_ID/portal-warp-api:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

